---
version: 2

sphinx:
  configuration: docs/conf.py

formats:
  - htmlzip
  - epub
  - pdf

python:
  version: 3.7
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
