---
name: "CI"
on: # yamllint disable-line rule:truthy rule:comments
  push:
    branches:
      - "main"
      - "develop"
    tags:
      - "v*"
  pull_request: ~

jobs:
  test:
    name: "Run Tests"
    runs-on: "ubuntu-20.04"
    steps:
      - name: "Check out repository code"
        uses: "actions/checkout@v2"
      - name: "Setup environment"
        uses: "networktocode/gh-action-setup-poetry-environment@v4"
      - name: "Run make tests"
        run: "make tests"
  publish:
    name: "Publish to PyPI"
    needs:
      - "test"
    runs-on: "ubuntu-20.04"
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: "Check out repository code"
        uses: "actions/checkout@v2"
      - name: "Setup environment"
        uses: "networktocode/gh-action-setup-poetry-environment@v4"
      - name: "Run make tests"
        run: "make tests"